src/config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'
  get 'pages/contact'
  get 'pages/pricing'
  get 'pages/about'
  get 'pages/washer'
  get 'pages/checkout'
  get 'pages/car_selection'

  devise_for :users, controllers: {
    registrations: 'user/registrations', only: [:create]
  }

  resources :cars
  resources :payments

  # # shows all contacts
  # get 'contact', as: 'contact#index'

  # # shows 1 contact
  # get 'contacts/:id', as: 'contact#show'

  # # page to input data for new contact
  # get 'contacts/new', as: 'contact#new'

  # # page to input data for editing a contact
  # get 'contacts/edit', as: 'contact#edit'

  # # destroys a contact
  # delete 'contacts/:id', as: 'contact#destroy'

  # # creates a new contact
  # post 'contacts', as: 'contact#create'

  # # updates a contact
  # patch 'contacts/:id', as: 'contact#update'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/views/pages/about.html.erb
<article class="message has-text-grey-lighter">
  <div class="message-header has-background-link">
    <p>About Us</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div class="message-body">
   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae, recusandae? <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
  </div>
</article>

<article class="message has-text-grey-lighter">
  <div class="message-header has-background-link">
    <p>Our Promise</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div class="message-body">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
  </div>
</article>

<article class="message has-text-grey-lighter">
  <div class="message-header has-background-link">
    <p>What we bring to you</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div class="message-body">
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus molestiae nesciunt in neque iste omnis ratione repudiandae doloremque commodi est ex cupiditate quibusdam, nisi sapiente minima inventore sint placeat? Porro explicabo omnis, ea eos quas error hic quibusdam nostrum veritatis. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
  </div>
</article>

<article class="message has-text-grey-lighter">
  <div class="message-header has-background-link">
    <p>We connect people</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div class="message-body">
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex totam maiores numquam. Consequuntur nulla reprehenderit quod ut, atque dolore distinctio beatae, similique, assumenda repellat est? <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
  </div>
</article>

src/app/views/pages/contact.html.erb
<article class="panel is-primary">
  <p class="panel-heading">
    GENERAL CONTACT
  </p>
  <div class="panel-block">
    <p class="control has-icons-left">
      <span class="icon is-left">
        <i class="fas fa-search" aria-hidden="true"></i>
      </span>
    </p>
  </div>
  <a class="panel-block is-active">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    Contact by Phone
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    EMAIL: 
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    FAX: 
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    PO BOX 0000, 13 Example street, Narnia.
  </a>
</article>

<article class="panel is-link">
  <p class="panel-heading">
    Vehicle Owners - Complaints/Issues
  </p>
  <div class="panel-block">
    <p class="control has-icons-left">
      <input class="input is-link" type="text" placeholder="Search">
      <span class="icon is-left">
        <i class="fas fa-search" aria-hidden="true"></i>
      </span>
    </p>
  </div>
  <a class="panel-block is-active">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    Call us on skype for a 24 hour automated service.
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
   For a payment issue, please contact:
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    <em>(07) 112 342 000 STR*PE</em>
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>

  </a>
</article>


<article class="panel is-info">
  <p class="panel-heading">
    Contact for Detailers
  </p>
  <div class="panel-block">
  </div>
  <a class="panel-block is-active">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ducimus doloremque. Adipisci, labore nemo? Mollitia, nisi cum fugit quas minus dignissimos eaque, quasi nobis distinctio quod ipsam earum dolor ab!
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    
  </a>
</article>

src/app/views/pages/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<% if user_signed_in? %>
  <% if current_user.image.attached? %>
    <%= image_tag current_user.image, width: 120 %>
  <% end %>
  <p>Hello,<%= current_user.first_name %></p>
<% end %>
    <div class="tile is-ancestor">
  <div class="tile is-vertical is-12">
    <div class="tile">
      <div class="tile is-parent is-vertical ">
        <article class="tile is-child notification has-background-white-ter	"></article>
        </article>
        <article class="tile is-child notification has-background-white-ter	">
          <p class="subtitle"><h1 class="title is-1 has-text-link" >Splash Auto Mobile Wash
      </div>
      <div class="tile is-parent has-background-white-ter	"><article class="tile is-child notification has-background-white-ter	"><img src="https://images.unsplash.com/photo-1565689876697-e467b6c54da2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80" alt="Smiley face" height="420" width="420">
      </article>
        <article class="tile is-child notification has-background-white-ter	">
          <figure class="image is-4by3">
        <div class="notification is-success">
  <button  class="delete"></button>
  Splash Auto Mobile Wash
</div>
<div class="notification is-info">
  <button class="delete"></button>
  Great for beginners
          </figure>
        </article>
      </div>
    </div>
    <div class="tile is-parent has-background-white-ter	">
    </div>
  </div>
    </article>
  </div>
</div>
</body>
</html>

src/app/views/pages/information.html.erb
<div class="pageloader"><span class="title">Pageloader</span></div>

src/app/views/pages/pricing.html.erb
<div class="pricing-table">
  <div class="pricing-plan is-primary">
  <div class="plan-header">Small Vehicle<br>(Sedan or Hatchback)</div>
  <div class="plan-header">Mini Detail Express</div>
    <div class="plan-price">
    <span class="plan-price-amount"><span class="plan-price-currency">$</span>$44.99</span>/vehicle</div>
    <div class="plan-items">
      <div class="plan-item">Special bubble foam hand wash</div>
      <div class="plan-item">Clean wheels and wheel arches</div>
      <div class="plan-item">Clean door jams</div>
      <div class="plan-item">Chamois dry</div>
      <div class="plan-item">Vacuum interior (seats, carpets, boot and ashtray)</div>
      <div class="plan-item">Blacken tyres</div>
      <div class="plan-item">Clean windows (inside and out)</div>
      <div class="plan-item">Deodorise</div>
      <div class="plan-item">Mirrors cleaned</div>
      <div class="plan-item">Clean windows (inside and out)</div>
    </div>
    <div class="plan-footer">
      <%= link_to 'Choose', new_car_path(price: 4499), class:"button is-fullwidth" %>
    </div>
  </div>

  <div class="pricing-plan is-link">
  <div class="plan-header">Medium Vehicle<br>(Wagon or small 4WD)<br></div>
    <div class="plan-header">Advanced Super-Express</div>
    <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>64.99</span>/vehicle</div>
    <div class="plan-items">
      <div class="plan-item">Special bubble foam hand wash</div>
      <div class="plan-item">Clean wheels and wheel arches</div>
      <div class="plan-item">Clean door jams</div>
      <div class="plan-item">Chamois dry</div>
      <div class="plan-item">Vacuum interior (seats, carpets, boot and ashtray)</div>
      <div class="plan-item">Blacken tyres</div>
      <div class="plan-item">Clean windows (inside and out)</div>
      <div class="plan-item">Deodorise</div>
      <div class="plan-item">Mirrors cleaned</div>
      <div class="plan-item">Clean windows (inside and out)</div>
    </div>
    <div class="plan-footer">
      <%= link_to 'Choose', new_car_path(price: 6499), class:"button is-fullwidth" %>
    </div>
  </div>

  <div class="pricing-plan is-success">
  <div class="plan-header is-danger">Large Vehicle<br>(Large 4WD or 7-8 SEATER)</div>
    <div class="plan-header is-danger">Super Express Pro</div>
    <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>84.99</span>/vehicle</div>
    <div class="plan-items">
      <div class="plan-item">Special bubble foam hand wash</div>
      <div class="plan-item">Clean wheels and wheel arches</div>
      <div class="plan-item">Clean door jams</div>
      <div class="plan-item">Chamois dry</div>
      <div class="plan-item">Vacuum interior (seats, carpets, boot and ashtray)</div>
      <div class="plan-item">Blacken tyres</div>
      <div class="plan-item">Clean windows (inside and out)</div>
      <div class="plan-item">Deodorise</div>
      <div class="plan-item">Mirrors cleaned</div>
      <div class="plan-item">Clean windows (inside and out)</div>
    </div>
    <div class="plan-footer">
      <%= link_to 'Choose', new_car_path(price: 8499), class:"button is-fullwidth" %>
    </div>
  </div>
</div>

src/app/views/pages/washer.html.erb
<table class="table">
  <thead>
    <tr>
      <th><abbr title="user_suburb">SUBURB</th>
    
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th><abbr title="car_type">SUBURB</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <th>1</th>
      <td><a href="https://en.wikipedia.org/wiki/Leicester_City_F.C." title="Leicester City F.C.">Leicester City</a> <strong>(C)</strong>
      </td>
      <td>38</td>
      <td>23</td>
      <td>12</td>
      <td>3</td>
      <td>68</td>
      <td>36</td>
      <td>+32</td>
      <td>81</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Champions_League#Group_stage" title="2016–17 UEFA Champions League">Champions League group stage</a></td>
    </tr>
    <tr>
      <th>2</th>
      <td><a href="https://en.wikipedia.org/wiki/Arsenal_F.C." title="Arsenal F.C.">Arsenal</a></td>
      <td>38</td>
      <td>20</td>
      <td>11</td>
      <td>7</td>
      <td>65</td>
      <td>36</td>
      <td>+29</td>
      <td>71</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Champions_League#Group_stage" title="2016–17 UEFA Champions League">Champions League group stage</a></td>
    </tr>
    <tr>
      <th>3</th>
      <td><a href="https://en.wikipedia.org/wiki/Tottenham_Hotspur_F.C." title="Tottenham Hotspur F.C.">Tottenham Hotspur</a></td>
      <td>38</td>
      <td>19</td>
      <td>13</td>
      <td>6</td>
      <td>69</td>
      <td>35</td>
      <td>+34</td>
      <td>70</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Champions_League#Group_stage" title="2016–17 UEFA Champions League">Champions League group stage</a></td>
    </tr>
    <tr class="is-selected">
      <th>4</th>
      <td><a href="https://en.wikipedia.org/wiki/Manchester_City_F.C." title="Manchester City F.C.">Manchester City</a></td>
      <td>38</td>
      <td>19</td>
      <td>9</td>
      <td>10</td>
      <td>71</td>
      <td>41</td>
      <td>+30</td>
      <td>66</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Champions_League#Play-off_round" title="2016–17 UEFA Champions League">Champions League play-off round</a></td>
    </tr>
    <tr>
      <th>5</th>
      <td><a href="https://en.wikipedia.org/wiki/Manchester_United_F.C." title="Manchester United F.C.">Manchester United</a></td>
      <td>38</td>
      <td>19</td>
      <td>9</td>
      <td>10</td>
      <td>49</td>
      <td>35</td>
      <td>+14</td>
      <td>66</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Europa_League#Group_stage" title="2016–17 UEFA Europa League">Europa League group stage</a></td>
    </tr>
    <tr>
      <th>6</th>
      <td><a href="https://en.wikipedia.org/wiki/Southampton_F.C." title="Southampton F.C.">Southampton</a></td>
      <td>38</td>
      <td>18</td>
      <td>9</td>
      <td>11</td>
      <td>59</td>
      <td>41</td>
      <td>+18</td>
      <td>63</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Europa_League#Group_stage" title="2016–17 UEFA Europa League">Europa League group stage</a></td>
    </tr>
    <tr>
      <th>7</th>
      <td><a href="https://en.wikipedia.org/wiki/West_Ham_United_F.C." title="West Ham United F.C.">West Ham United</a></td>
      <td>38</td>
      <td>16</td>
      <td>14</td>
      <td>8</td>
      <td>65</td>
      <td>51</td>
      <td>+14</td>
      <td>62</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Europa_League#Third_qualifying_round" title="2016–17 UEFA Europa League">Europa League third qualifying round</a></td>
    </tr>
    <tr>
      <th>8</th>
      <td><a href="https://en.wikipedia.org/wiki/Liverpool_F.C." title="Liverpool F.C.">Liverpool</a></td>
      <td>38</td>
      <td>16</td>
      <td>12</td>
      <td>10</td>
      <td>63</td>
      <td>50</td>
      <td>+13</td>
      <td>60</td>
      <td></td>
    </tr>
</table>