src/config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'
  get 'pages/contact'
  get 'pages/pricing'
  get 'pages/about'
  get 'pages/washer'
  get 'pages/checkout'
  get 'pages/car_selection'

  devise_for :users, controllers: {
    registrations: 'user/registrations', only: [:create]
  }

  resources :cars
  resources :payments

  # # shows all contacts
  # get 'contact', as: 'contact#index'

  # # shows 1 contact
  # get 'contacts/:id', as: 'contact#show'

  # # page to input data for new contact
  # get 'contacts/new', as: 'contact#new'

  # # page to input data for editing a contact
  # get 'contacts/edit', as: 'contact#edit'

  # # destroys a contact
  # delete 'contacts/:id', as: 'contact#destroy'

  # # creates a new contact
  # post 'contacts', as: 'contact#create'

  # # updates a contact
  # patch 'contacts/:id', as: 'contact#update'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Splash Auto Mobile Wash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to '<img src="https://seeklogo.com/images/S/Splash-logo-F4F9BFE608-seeklogo.com.png" width="112" height="28">'.html_safe, root_path, class: "navbar-item" %>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to 'Pricing', pages_pricing_path, class: "navbar-item" %>
          <%= link_to 'About us', pages_about_path, class: "navbar-item" %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <em>Washers</em>
            </a>

            <div class="navbar-dropdown">
              <%= link_to 'Jobs', cars_path, class: "navbar-item" %>
              <%= link_to 'Contact us 24/7', pages_contact_path, class: "navbar-item" %>
              <hr class="navbar-divider">
            </div>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete', class: 'button is-warning' %>
              <% else %>
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-success" %>
                <%= link_to 'Sign In', new_user_session_path, class: 'button is-info' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <% if flash[:error] %>
      <p class='error'><%= flash[:error] %></p>
    <% elsif flash[:success] %>

    <% end %>

    <%= yield %>

    <br />
    <br />
    <footer class="btmnav ">
      <div class="content has-text-centered">
        <p>
          <strong>Splash Auto Wash</strong> by <a href="https://paveldemeter.github.io/portfolio/index.html">Pavel Demeter</a>. The website content
          is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Pavel Demeter ©</a>.
        </p>
      </div>
    </footer> 
  </body>
</html>